# Generated by Django 3.2.16 on 2024-08-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240829_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_following',
        ),
    ]
